# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-08-07 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf')),
                ('name_surname', models.CharField(max_length=120, verbose_name='Ad Soyad')),
                ('tc_no', models.CharField(max_length=11, verbose_name='TC Kimlik Numarası')),
                ('email', models.CharField(max_length=120, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=14, verbose_name='Telefon')),
                ('address', models.CharField(max_length=150, verbose_name='Adres')),
                ('city', models.CharField(choices=[('Adana', 'Adana'), ('Adıyaman', 'Adıyaman'), ('Afyon', 'Afyon'), ('Ağrı', 'Ağrı'), ('Amasya', 'Amasya'), ('Ankara', 'Ankara'), ('Antalya', 'Antalya'), ('Artvin', 'Artvin'), ('Aydın', 'Aydın'), ('Balıkesir', 'Balıkesir'), ('Bilecik', 'Bilecik'), ('Bingöl', 'Bingöl'), ('Bitlis', 'Bitlis'), ('Bolu', 'Bolu'), ('Burdur', 'Burdur'), ('Bursa', 'Bursa'), ('Çanakkale', 'Çanakkale'), ('Çankırı', 'Çankırı'), ('Çorum', 'Çorum'), ('Denizli', 'Denizli'), ('Diyarbakır', 'Diyarbakır'), ('Edirne', 'Edirne'), ('Elazığ', 'Elazığ'), ('Erzincan', 'Erzincan'), ('Erzurum', 'Erzurum'), ('Eskişehir', 'Eskişehir'), ('Gaziantep', 'Gaziantep'), ('Giresun', 'Giresun'), ('Gümüşhane', 'Gümüşhane'), ('Hakkari', 'Hakkari'), ('Hatay', 'Hatay'), ('Isparta', 'Isparta'), ('Mersin', 'Mersin'), ('İstanbul', 'İstanbul'), ('İzmir', 'İzmir'), ('Kars', 'Kars'), ('Kastamonu', 'Kastamonu'), ('Kayseri', 'Kayseri'), ('Kırklareli', 'Kırklareli'), ('Kırşehir', 'Kırşehir'), ('Kocaeli', 'Kocaeli'), ('Konya', 'Konya'), ('Kütahya', 'Kütahya'), ('Malatya', 'Malatya'), ('Manisa', 'Manisa'), ('Kahramanmaraş', 'Kahramanmaraş'), ('Mardin', 'Mardin'), ('Muğla', 'Muğla'), ('Muş', 'Muş'), ('Nevşehir', 'Nevşehir'), ('Niğde', 'Niğde'), ('Ordu', 'Ordu'), ('Rize', 'Rize'), ('Sakarya', 'Sakarya'), ('Samsun', 'Samsun'), ('Siirt', 'Siirt'), ('Sinop', 'Sinop'), ('Sivas', 'Sivas'), ('Tekirdağ', 'Tekirdağ'), ('Tokat', 'Tokat'), ('Trabzon', 'Trabzon'), ('Tunceli', 'Tunceli'), ('Şanlıurfa', 'Şanlıurfa'), ('Uşak', 'Uşak'), ('Van', 'Van'), ('Yozgat', 'Yozgat'), ('Zonguldak', 'Zonguldak'), ('Aksaray', 'Aksaray'), ('Bayburt', 'Bayburt'), ('Karaman', 'Karaman'), ('Kırıkkale', 'Kırıkkale'), ('Batman', 'Batman'), ('Şırnak', 'Şırnak'), ('Bartın', 'Bartın'), ('Ardahan', 'Ardahan'), ('Iğdır', 'Iğdır'), ('Yalova', 'Yalova'), ('Karabük', 'Karabük'), ('Kilis', 'Kilis'), ('Osmaniye', 'Osmaniye'), ('Düzce', 'Düzce')], max_length=120, verbose_name='Yaşadığı Şehir')),
                ('job', models.CharField(choices=[('Doktor', 'Doktor'), ('Ev Hanımı', 'Ev Hanımı'), ('Öğretmen', 'Öğretmen'), ('Mühendis', 'Mühendis'), ('Şoför', 'Şoför'), ('Garson', 'Garson'), ('Diğer', 'Diğer')], max_length=120, verbose_name='Meslek')),
                ('education_grade', models.CharField(choices=[('İlkokul', 'İlkokul'), ('Lise', 'Lise'), ('Lisans', 'Lisans'), ('Master', 'Master'), ('Okumadı', 'Okumadı')], max_length=120, verbose_name='Eğitim Düzeyi')),
                ('birthdate', models.DateField(verbose_name='Doğum Tarihi')),
                ('referrence', models.CharField(max_length=120, verbose_name='Referans Kodu')),
                ('confirmation', models.BooleanField(verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ürün Adı')),
                ('price', models.CharField(max_length=120, verbose_name='Ürün Fiyatı')),
                ('discount', models.CharField(max_length=120, verbose_name='İndirimli Fiyatı')),
                ('available_number', models.CharField(max_length=120, verbose_name='Stok Adedi')),
                ('category', models.CharField(choices=[('Otomotiv', 'Otomotiv'), ('Sağlık', 'Sağlık'), ('Eğitim', 'Eğitim')], max_length=120, verbose_name='Ürün Kategorisi')),
                ('tag', models.CharField(choices=[('Yeni', 'Yeni'), ('Son3', 'Son3'), ('Son2', 'Son2'), ('Özel', 'Özel'), ('Stok Yok', 'Stok Yok')], max_length=120, verbose_name='Ürün Tag')),
                ('range1', models.DateField(verbose_name='İndirimli Fiyat Aralığı')),
                ('range2', models.DateField(verbose_name='')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Ürün Ana Görseli')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Ürün Galeri')),
            ],
        ),
        migrations.CreateModel(
            name='AddUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf')),
                ('name_surname', models.CharField(max_length=120, verbose_name='Ad Soyad')),
                ('tc_no', models.CharField(max_length=11, verbose_name='TC Kimlik Numarası')),
                ('email', models.CharField(max_length=120, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=14, verbose_name='Telefon')),
                ('address', models.CharField(max_length=150, verbose_name='Adres')),
                ('city', models.CharField(choices=[('Adana', 'Adana'), ('Adıyaman', 'Adıyaman'), ('Afyon', 'Afyon'), ('Ağrı', 'Ağrı'), ('Amasya', 'Amasya'), ('Ankara', 'Ankara'), ('Antalya', 'Antalya'), ('Artvin', 'Artvin'), ('Aydın', 'Aydın'), ('Balıkesir', 'Balıkesir'), ('Bilecik', 'Bilecik'), ('Bingöl', 'Bingöl'), ('Bitlis', 'Bitlis'), ('Bolu', 'Bolu'), ('Burdur', 'Burdur'), ('Bursa', 'Bursa'), ('Çanakkale', 'Çanakkale'), ('Çankırı', 'Çankırı'), ('Çorum', 'Çorum'), ('Denizli', 'Denizli'), ('Diyarbakır', 'Diyarbakır'), ('Edirne', 'Edirne'), ('Elazığ', 'Elazığ'), ('Erzincan', 'Erzincan'), ('Erzurum', 'Erzurum'), ('Eskişehir', 'Eskişehir'), ('Gaziantep', 'Gaziantep'), ('Giresun', 'Giresun'), ('Gümüşhane', 'Gümüşhane'), ('Hakkari', 'Hakkari'), ('Hatay', 'Hatay'), ('Isparta', 'Isparta'), ('Mersin', 'Mersin'), ('İstanbul', 'İstanbul'), ('İzmir', 'İzmir'), ('Kars', 'Kars'), ('Kastamonu', 'Kastamonu'), ('Kayseri', 'Kayseri'), ('Kırklareli', 'Kırklareli'), ('Kırşehir', 'Kırşehir'), ('Kocaeli', 'Kocaeli'), ('Konya', 'Konya'), ('Kütahya', 'Kütahya'), ('Malatya', 'Malatya'), ('Manisa', 'Manisa'), ('Kahramanmaraş', 'Kahramanmaraş'), ('Mardin', 'Mardin'), ('Muğla', 'Muğla'), ('Muş', 'Muş'), ('Nevşehir', 'Nevşehir'), ('Niğde', 'Niğde'), ('Ordu', 'Ordu'), ('Rize', 'Rize'), ('Sakarya', 'Sakarya'), ('Samsun', 'Samsun'), ('Siirt', 'Siirt'), ('Sinop', 'Sinop'), ('Sivas', 'Sivas'), ('Tekirdağ', 'Tekirdağ'), ('Tokat', 'Tokat'), ('Trabzon', 'Trabzon'), ('Tunceli', 'Tunceli'), ('Şanlıurfa', 'Şanlıurfa'), ('Uşak', 'Uşak'), ('Van', 'Van'), ('Yozgat', 'Yozgat'), ('Zonguldak', 'Zonguldak'), ('Aksaray', 'Aksaray'), ('Bayburt', 'Bayburt'), ('Karaman', 'Karaman'), ('Kırıkkale', 'Kırıkkale'), ('Batman', 'Batman'), ('Şırnak', 'Şırnak'), ('Bartın', 'Bartın'), ('Ardahan', 'Ardahan'), ('Iğdır', 'Iğdır'), ('Yalova', 'Yalova'), ('Karabük', 'Karabük'), ('Kilis', 'Kilis'), ('Osmaniye', 'Osmaniye'), ('Düzce', 'Düzce')], max_length=120, verbose_name='Yaşadığı Şehir')),
                ('job', models.CharField(choices=[('Doktor', 'Doktor'), ('Ev Hanımı', 'Ev Hanımı'), ('Öğretmen', 'Öğretmen'), ('Mühendis', 'Mühendis'), ('Şoför', 'Şoför'), ('Garson', 'Garson'), ('Diğer', 'Diğer')], max_length=120, verbose_name='Meslek')),
                ('education_grade', models.CharField(choices=[('İlkokul', 'İlkokul'), ('Lise', 'Lise'), ('Lisans', 'Lisans'), ('Master', 'Master'), ('Okumadı', 'Okumadı')], max_length=120, verbose_name='Eğitim Düzeyi')),
                ('birthdate', models.DateField(verbose_name='Doğum Tarihi')),
                ('referrence', models.CharField(max_length=120, verbose_name='Referans Kodu')),
                ('confirmation', models.BooleanField(verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='İl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('il', models.CharField(max_length=100, verbose_name='İl')),
            ],
        ),
        migrations.CreateModel(
            name='İlçe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilçe', models.CharField(max_length=100, verbose_name='İlçe')),
                ('il', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KullanıcıEkle.İl')),
            ],
        ),
        migrations.CreateModel(
            name='SiparişEkle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanıcı', models.CharField(max_length=100, verbose_name='Kullanıcı')),
                ('ürün', models.CharField(max_length=120, verbose_name='Ürün Adı')),
                ('adet', models.CharField(max_length=120, verbose_name='Adet')),
                ('adres', models.CharField(max_length=120, verbose_name='Adres')),
                ('kredi', models.BooleanField(verbose_name='Kredi Kartı')),
                ('eft', models.BooleanField(verbose_name='EFT/Havale')),
                ('onayla', models.BooleanField(verbose_name='')),
                ('il', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='KullanıcıEkle.İl', verbose_name='İl')),
                ('ilçe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='KullanıcıEkle.İlçe', verbose_name='İlçe')),
            ],
        ),
    ]
